/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * You are not allowed to enable the API.
 */
export type EnableApiResponseBodyData = {
  message?: string | undefined;
};

/**
 * You are not allowed to enable the API.
 */
export class EnableApiResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: EnableApiResponseBodyData;

  constructor(err: EnableApiResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "EnableApiResponseBody";
  }
}

/** @internal */
export const EnableApiResponseBody$inboundSchema: z.ZodType<
  EnableApiResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
})
  .transform((v) => {
    return new EnableApiResponseBody(v);
  });

/** @internal */
export type EnableApiResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const EnableApiResponseBody$outboundSchema: z.ZodType<
  EnableApiResponseBody$Outbound,
  z.ZodTypeDef,
  EnableApiResponseBody
> = z.instanceof(EnableApiResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnableApiResponseBody$ {
  /** @deprecated use `EnableApiResponseBody$inboundSchema` instead. */
  export const inboundSchema = EnableApiResponseBody$inboundSchema;
  /** @deprecated use `EnableApiResponseBody$outboundSchema` instead. */
  export const outboundSchema = EnableApiResponseBody$outboundSchema;
  /** @deprecated use `EnableApiResponseBody$Outbound` instead. */
  export type Outbound = EnableApiResponseBody$Outbound;
}
