/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDisable } from "../funcs/apiDisable.js";
import { apiEnable } from "../funcs/apiEnable.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api extends ClientSDK {
  /**
   * Enable API
   *
   * @remarks
   * Enable API (only with root permissions).
   */
  async enable(
    options?: RequestOptions,
  ): Promise<operations.EnableApiResponseBody> {
    return unwrapAsync(apiEnable(
      this,
      options,
    ));
  }

  /**
   * Disable API
   *
   * @remarks
   * Disable API (only with root permissions).
   */
  async disable(
    options?: RequestOptions,
  ): Promise<operations.DisableApiResponseBody> {
    return unwrapAsync(apiDisable(
      this,
      options,
    ));
  }
}
