/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesList } from "../funcs/resourcesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Resources extends ClientSDK {
  /**
   * List
   *
   * @remarks
   * Get all resources.
   */
  async list(
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(resourcesList(
      this,
      options,
    ));
  }
}
