/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Api } from "./api.js";
import { Applications } from "./applications.js";
import { Databases } from "./databases.js";
import { Deployments } from "./deployments.js";
import { Health } from "./health.js";
import { PrivateKeys } from "./privatekeys.js";
import { Projects } from "./projects.js";
import { Resources } from "./resources.js";
import { Servers } from "./servers.js";
import { Services } from "./services.js";
import { Teams } from "./teams.js";
import { Version } from "./version.js";

export class Coolify extends ClientSDK {
  private _applications?: Applications;
  get applications(): Applications {
    return (this._applications ??= new Applications(this._options));
  }

  private _databases?: Databases;
  get databases(): Databases {
    return (this._databases ??= new Databases(this._options));
  }

  private _deployments?: Deployments;
  get deployments(): Deployments {
    return (this._deployments ??= new Deployments(this._options));
  }

  private _version?: Version;
  get version(): Version {
    return (this._version ??= new Version(this._options));
  }

  private _api?: Api;
  get api(): Api {
    return (this._api ??= new Api(this._options));
  }

  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }

  private _projects?: Projects;
  get projects(): Projects {
    return (this._projects ??= new Projects(this._options));
  }

  private _resources?: Resources;
  get resources(): Resources {
    return (this._resources ??= new Resources(this._options));
  }

  private _privateKeys?: PrivateKeys;
  get privateKeys(): PrivateKeys {
    return (this._privateKeys ??= new PrivateKeys(this._options));
  }

  private _servers?: Servers;
  get servers(): Servers {
    return (this._servers ??= new Servers(this._options));
  }

  private _services?: Services;
  get services(): Services {
    return (this._services ??= new Services(this._options));
  }

  private _teams?: Teams;
  get teams(): Teams {
    return (this._teams ??= new Teams(this._options));
  }
}
