/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeletePrivateKeyByUuidRequest = {
  /**
   * Private Key UUID
   */
  uuid: string;
};

/**
 * Private Key deleted.
 */
export type DeletePrivateKeyByUuidResponseBody = {
  message?: string | undefined;
};

/** @internal */
export const DeletePrivateKeyByUuidRequest$inboundSchema: z.ZodType<
  DeletePrivateKeyByUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type DeletePrivateKeyByUuidRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeletePrivateKeyByUuidRequest$outboundSchema: z.ZodType<
  DeletePrivateKeyByUuidRequest$Outbound,
  z.ZodTypeDef,
  DeletePrivateKeyByUuidRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeletePrivateKeyByUuidRequest$ {
  /** @deprecated use `DeletePrivateKeyByUuidRequest$inboundSchema` instead. */
  export const inboundSchema = DeletePrivateKeyByUuidRequest$inboundSchema;
  /** @deprecated use `DeletePrivateKeyByUuidRequest$outboundSchema` instead. */
  export const outboundSchema = DeletePrivateKeyByUuidRequest$outboundSchema;
  /** @deprecated use `DeletePrivateKeyByUuidRequest$Outbound` instead. */
  export type Outbound = DeletePrivateKeyByUuidRequest$Outbound;
}

export function deletePrivateKeyByUuidRequestToJSON(
  deletePrivateKeyByUuidRequest: DeletePrivateKeyByUuidRequest,
): string {
  return JSON.stringify(
    DeletePrivateKeyByUuidRequest$outboundSchema.parse(
      deletePrivateKeyByUuidRequest,
    ),
  );
}

export function deletePrivateKeyByUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeletePrivateKeyByUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePrivateKeyByUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePrivateKeyByUuidRequest' from JSON`,
  );
}

/** @internal */
export const DeletePrivateKeyByUuidResponseBody$inboundSchema: z.ZodType<
  DeletePrivateKeyByUuidResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type DeletePrivateKeyByUuidResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const DeletePrivateKeyByUuidResponseBody$outboundSchema: z.ZodType<
  DeletePrivateKeyByUuidResponseBody$Outbound,
  z.ZodTypeDef,
  DeletePrivateKeyByUuidResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeletePrivateKeyByUuidResponseBody$ {
  /** @deprecated use `DeletePrivateKeyByUuidResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeletePrivateKeyByUuidResponseBody$inboundSchema;
  /** @deprecated use `DeletePrivateKeyByUuidResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    DeletePrivateKeyByUuidResponseBody$outboundSchema;
  /** @deprecated use `DeletePrivateKeyByUuidResponseBody$Outbound` instead. */
  export type Outbound = DeletePrivateKeyByUuidResponseBody$Outbound;
}

export function deletePrivateKeyByUuidResponseBodyToJSON(
  deletePrivateKeyByUuidResponseBody: DeletePrivateKeyByUuidResponseBody,
): string {
  return JSON.stringify(
    DeletePrivateKeyByUuidResponseBody$outboundSchema.parse(
      deletePrivateKeyByUuidResponseBody,
    ),
  );
}

export function deletePrivateKeyByUuidResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeletePrivateKeyByUuidResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePrivateKeyByUuidResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePrivateKeyByUuidResponseBody' from JSON`,
  );
}
