/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteServiceByUuidRequest = {
  /**
   * Service UUID
   */
  uuid: string;
  /**
   * Delete configurations.
   */
  deleteConfigurations?: boolean | undefined;
  /**
   * Delete volumes.
   */
  deleteVolumes?: boolean | undefined;
  /**
   * Run docker cleanup.
   */
  dockerCleanup?: boolean | undefined;
  /**
   * Delete connected networks.
   */
  deleteConnectedNetworks?: boolean | undefined;
};

/**
 * Delete a service by UUID
 */
export type DeleteServiceByUuidResponseBody = {
  message?: string | undefined;
};

/** @internal */
export const DeleteServiceByUuidRequest$inboundSchema: z.ZodType<
  DeleteServiceByUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  delete_configurations: z.boolean().default(true),
  delete_volumes: z.boolean().default(true),
  docker_cleanup: z.boolean().default(true),
  delete_connected_networks: z.boolean().default(true),
}).transform((v) => {
  return remap$(v, {
    "delete_configurations": "deleteConfigurations",
    "delete_volumes": "deleteVolumes",
    "docker_cleanup": "dockerCleanup",
    "delete_connected_networks": "deleteConnectedNetworks",
  });
});

/** @internal */
export type DeleteServiceByUuidRequest$Outbound = {
  uuid: string;
  delete_configurations: boolean;
  delete_volumes: boolean;
  docker_cleanup: boolean;
  delete_connected_networks: boolean;
};

/** @internal */
export const DeleteServiceByUuidRequest$outboundSchema: z.ZodType<
  DeleteServiceByUuidRequest$Outbound,
  z.ZodTypeDef,
  DeleteServiceByUuidRequest
> = z.object({
  uuid: z.string(),
  deleteConfigurations: z.boolean().default(true),
  deleteVolumes: z.boolean().default(true),
  dockerCleanup: z.boolean().default(true),
  deleteConnectedNetworks: z.boolean().default(true),
}).transform((v) => {
  return remap$(v, {
    deleteConfigurations: "delete_configurations",
    deleteVolumes: "delete_volumes",
    dockerCleanup: "docker_cleanup",
    deleteConnectedNetworks: "delete_connected_networks",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteServiceByUuidRequest$ {
  /** @deprecated use `DeleteServiceByUuidRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteServiceByUuidRequest$inboundSchema;
  /** @deprecated use `DeleteServiceByUuidRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteServiceByUuidRequest$outboundSchema;
  /** @deprecated use `DeleteServiceByUuidRequest$Outbound` instead. */
  export type Outbound = DeleteServiceByUuidRequest$Outbound;
}

export function deleteServiceByUuidRequestToJSON(
  deleteServiceByUuidRequest: DeleteServiceByUuidRequest,
): string {
  return JSON.stringify(
    DeleteServiceByUuidRequest$outboundSchema.parse(deleteServiceByUuidRequest),
  );
}

export function deleteServiceByUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteServiceByUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteServiceByUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteServiceByUuidRequest' from JSON`,
  );
}

/** @internal */
export const DeleteServiceByUuidResponseBody$inboundSchema: z.ZodType<
  DeleteServiceByUuidResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type DeleteServiceByUuidResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const DeleteServiceByUuidResponseBody$outboundSchema: z.ZodType<
  DeleteServiceByUuidResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteServiceByUuidResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteServiceByUuidResponseBody$ {
  /** @deprecated use `DeleteServiceByUuidResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteServiceByUuidResponseBody$inboundSchema;
  /** @deprecated use `DeleteServiceByUuidResponseBody$outboundSchema` instead. */
  export const outboundSchema = DeleteServiceByUuidResponseBody$outboundSchema;
  /** @deprecated use `DeleteServiceByUuidResponseBody$Outbound` instead. */
  export type Outbound = DeleteServiceByUuidResponseBody$Outbound;
}

export function deleteServiceByUuidResponseBodyToJSON(
  deleteServiceByUuidResponseBody: DeleteServiceByUuidResponseBody,
): string {
  return JSON.stringify(
    DeleteServiceByUuidResponseBody$outboundSchema.parse(
      deleteServiceByUuidResponseBody,
    ),
  );
}

export function deleteServiceByUuidResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteServiceByUuidResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteServiceByUuidResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteServiceByUuidResponseBody' from JSON`,
  );
}
