/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Disable API.
 */
export type DisableApiResponseBody = {
  message?: string | undefined;
};

/** @internal */
export const DisableApiResponseBody$inboundSchema: z.ZodType<
  DisableApiResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type DisableApiResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const DisableApiResponseBody$outboundSchema: z.ZodType<
  DisableApiResponseBody$Outbound,
  z.ZodTypeDef,
  DisableApiResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DisableApiResponseBody$ {
  /** @deprecated use `DisableApiResponseBody$inboundSchema` instead. */
  export const inboundSchema = DisableApiResponseBody$inboundSchema;
  /** @deprecated use `DisableApiResponseBody$outboundSchema` instead. */
  export const outboundSchema = DisableApiResponseBody$outboundSchema;
  /** @deprecated use `DisableApiResponseBody$Outbound` instead. */
  export type Outbound = DisableApiResponseBody$Outbound;
}

export function disableApiResponseBodyToJSON(
  disableApiResponseBody: DisableApiResponseBody,
): string {
  return JSON.stringify(
    DisableApiResponseBody$outboundSchema.parse(disableApiResponseBody),
  );
}

export function disableApiResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DisableApiResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisableApiResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisableApiResponseBody' from JSON`,
  );
}
