/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDatabaseByUuidRequest = {
  /**
   * UUID of the database.
   */
  uuid: string;
};

/** @internal */
export const GetDatabaseByUuidRequest$inboundSchema: z.ZodType<
  GetDatabaseByUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type GetDatabaseByUuidRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetDatabaseByUuidRequest$outboundSchema: z.ZodType<
  GetDatabaseByUuidRequest$Outbound,
  z.ZodTypeDef,
  GetDatabaseByUuidRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDatabaseByUuidRequest$ {
  /** @deprecated use `GetDatabaseByUuidRequest$inboundSchema` instead. */
  export const inboundSchema = GetDatabaseByUuidRequest$inboundSchema;
  /** @deprecated use `GetDatabaseByUuidRequest$outboundSchema` instead. */
  export const outboundSchema = GetDatabaseByUuidRequest$outboundSchema;
  /** @deprecated use `GetDatabaseByUuidRequest$Outbound` instead. */
  export type Outbound = GetDatabaseByUuidRequest$Outbound;
}

export function getDatabaseByUuidRequestToJSON(
  getDatabaseByUuidRequest: GetDatabaseByUuidRequest,
): string {
  return JSON.stringify(
    GetDatabaseByUuidRequest$outboundSchema.parse(getDatabaseByUuidRequest),
  );
}

export function getDatabaseByUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetDatabaseByUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDatabaseByUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDatabaseByUuidRequest' from JSON`,
  );
}
