/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDeploymentByUuidRequest = {
  /**
   * Deployment UUID
   */
  uuid: string;
};

/** @internal */
export const GetDeploymentByUuidRequest$inboundSchema: z.ZodType<
  GetDeploymentByUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type GetDeploymentByUuidRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetDeploymentByUuidRequest$outboundSchema: z.ZodType<
  GetDeploymentByUuidRequest$Outbound,
  z.ZodTypeDef,
  GetDeploymentByUuidRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDeploymentByUuidRequest$ {
  /** @deprecated use `GetDeploymentByUuidRequest$inboundSchema` instead. */
  export const inboundSchema = GetDeploymentByUuidRequest$inboundSchema;
  /** @deprecated use `GetDeploymentByUuidRequest$outboundSchema` instead. */
  export const outboundSchema = GetDeploymentByUuidRequest$outboundSchema;
  /** @deprecated use `GetDeploymentByUuidRequest$Outbound` instead. */
  export type Outbound = GetDeploymentByUuidRequest$Outbound;
}

export function getDeploymentByUuidRequestToJSON(
  getDeploymentByUuidRequest: GetDeploymentByUuidRequest,
): string {
  return JSON.stringify(
    GetDeploymentByUuidRequest$outboundSchema.parse(getDeploymentByUuidRequest),
  );
}

export function getDeploymentByUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetDeploymentByUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDeploymentByUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDeploymentByUuidRequest' from JSON`,
  );
}
