/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetProjectByUuidRequest = {
  /**
   * Project UUID
   */
  uuid: string;
};

/** @internal */
export const GetProjectByUuidRequest$inboundSchema: z.ZodType<
  GetProjectByUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type GetProjectByUuidRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetProjectByUuidRequest$outboundSchema: z.ZodType<
  GetProjectByUuidRequest$Outbound,
  z.ZodTypeDef,
  GetProjectByUuidRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProjectByUuidRequest$ {
  /** @deprecated use `GetProjectByUuidRequest$inboundSchema` instead. */
  export const inboundSchema = GetProjectByUuidRequest$inboundSchema;
  /** @deprecated use `GetProjectByUuidRequest$outboundSchema` instead. */
  export const outboundSchema = GetProjectByUuidRequest$outboundSchema;
  /** @deprecated use `GetProjectByUuidRequest$Outbound` instead. */
  export type Outbound = GetProjectByUuidRequest$Outbound;
}

export function getProjectByUuidRequestToJSON(
  getProjectByUuidRequest: GetProjectByUuidRequest,
): string {
  return JSON.stringify(
    GetProjectByUuidRequest$outboundSchema.parse(getProjectByUuidRequest),
  );
}

export function getProjectByUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetProjectByUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProjectByUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProjectByUuidRequest' from JSON`,
  );
}
