/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPrivateKeyByUuidRequest = {
  /**
   * Private Key UUID
   */
  uuid: string;
};

/** @internal */
export const GetPrivateKeyByUuidRequest$inboundSchema: z.ZodType<
  GetPrivateKeyByUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type GetPrivateKeyByUuidRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetPrivateKeyByUuidRequest$outboundSchema: z.ZodType<
  GetPrivateKeyByUuidRequest$Outbound,
  z.ZodTypeDef,
  GetPrivateKeyByUuidRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPrivateKeyByUuidRequest$ {
  /** @deprecated use `GetPrivateKeyByUuidRequest$inboundSchema` instead. */
  export const inboundSchema = GetPrivateKeyByUuidRequest$inboundSchema;
  /** @deprecated use `GetPrivateKeyByUuidRequest$outboundSchema` instead. */
  export const outboundSchema = GetPrivateKeyByUuidRequest$outboundSchema;
  /** @deprecated use `GetPrivateKeyByUuidRequest$Outbound` instead. */
  export type Outbound = GetPrivateKeyByUuidRequest$Outbound;
}

export function getPrivateKeyByUuidRequestToJSON(
  getPrivateKeyByUuidRequest: GetPrivateKeyByUuidRequest,
): string {
  return JSON.stringify(
    GetPrivateKeyByUuidRequest$outboundSchema.parse(getPrivateKeyByUuidRequest),
  );
}

export function getPrivateKeyByUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPrivateKeyByUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPrivateKeyByUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPrivateKeyByUuidRequest' from JSON`,
  );
}
