/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetServiceByUuidRequest = {
  /**
   * Service UUID
   */
  uuid: string;
};

/** @internal */
export const GetServiceByUuidRequest$inboundSchema: z.ZodType<
  GetServiceByUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type GetServiceByUuidRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetServiceByUuidRequest$outboundSchema: z.ZodType<
  GetServiceByUuidRequest$Outbound,
  z.ZodTypeDef,
  GetServiceByUuidRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetServiceByUuidRequest$ {
  /** @deprecated use `GetServiceByUuidRequest$inboundSchema` instead. */
  export const inboundSchema = GetServiceByUuidRequest$inboundSchema;
  /** @deprecated use `GetServiceByUuidRequest$outboundSchema` instead. */
  export const outboundSchema = GetServiceByUuidRequest$outboundSchema;
  /** @deprecated use `GetServiceByUuidRequest$Outbound` instead. */
  export type Outbound = GetServiceByUuidRequest$Outbound;
}

export function getServiceByUuidRequestToJSON(
  getServiceByUuidRequest: GetServiceByUuidRequest,
): string {
  return JSON.stringify(
    GetServiceByUuidRequest$outboundSchema.parse(getServiceByUuidRequest),
  );
}

export function getServiceByUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetServiceByUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetServiceByUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetServiceByUuidRequest' from JSON`,
  );
}
