/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListEnvsByServiceUuidRequest = {
  /**
   * UUID of the service.
   */
  uuid: string;
};

/** @internal */
export const ListEnvsByServiceUuidRequest$inboundSchema: z.ZodType<
  ListEnvsByServiceUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type ListEnvsByServiceUuidRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const ListEnvsByServiceUuidRequest$outboundSchema: z.ZodType<
  ListEnvsByServiceUuidRequest$Outbound,
  z.ZodTypeDef,
  ListEnvsByServiceUuidRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListEnvsByServiceUuidRequest$ {
  /** @deprecated use `ListEnvsByServiceUuidRequest$inboundSchema` instead. */
  export const inboundSchema = ListEnvsByServiceUuidRequest$inboundSchema;
  /** @deprecated use `ListEnvsByServiceUuidRequest$outboundSchema` instead. */
  export const outboundSchema = ListEnvsByServiceUuidRequest$outboundSchema;
  /** @deprecated use `ListEnvsByServiceUuidRequest$Outbound` instead. */
  export type Outbound = ListEnvsByServiceUuidRequest$Outbound;
}

export function listEnvsByServiceUuidRequestToJSON(
  listEnvsByServiceUuidRequest: ListEnvsByServiceUuidRequest,
): string {
  return JSON.stringify(
    ListEnvsByServiceUuidRequest$outboundSchema.parse(
      listEnvsByServiceUuidRequest,
    ),
  );
}

export function listEnvsByServiceUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListEnvsByServiceUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEnvsByServiceUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEnvsByServiceUuidRequest' from JSON`,
  );
}
