/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The build pack type.
 */
export const UpdateApplicationByUuidBuildPack = {
  Nixpacks: "nixpacks",
  Static: "static",
  Dockerfile: "dockerfile",
  Dockercompose: "dockercompose",
} as const;
/**
 * The build pack type.
 */
export type UpdateApplicationByUuidBuildPack = ClosedEnum<
  typeof UpdateApplicationByUuidBuildPack
>;

/**
 * How to set redirect with Traefik / Caddy. www<->non-www.
 */
export const UpdateApplicationByUuidRedirect = {
  Www: "www",
  NonWww: "non-www",
  Both: "both",
} as const;
/**
 * How to set redirect with Traefik / Caddy. www<->non-www.
 */
export type UpdateApplicationByUuidRedirect = ClosedEnum<
  typeof UpdateApplicationByUuidRedirect
>;

/**
 * Application updated.
 */
export type UpdateApplicationByUuidRequestBody = {
  /**
   * The project UUID.
   */
  projectUuid?: string | undefined;
  /**
   * The server UUID.
   */
  serverUuid?: string | undefined;
  /**
   * The environment name.
   */
  environmentName?: string | undefined;
  /**
   * The Github App UUID.
   */
  githubAppUuid?: string | undefined;
  /**
   * The git repository URL.
   */
  gitRepository?: string | undefined;
  /**
   * The git branch.
   */
  gitBranch?: string | undefined;
  /**
   * The ports to expose.
   */
  portsExposes?: string | undefined;
  /**
   * The destination UUID.
   */
  destinationUuid?: string | undefined;
  /**
   * The build pack type.
   */
  buildPack?: UpdateApplicationByUuidBuildPack | undefined;
  /**
   * The application name.
   */
  name?: string | undefined;
  /**
   * The application description.
   */
  description?: string | undefined;
  /**
   * The application domains.
   */
  domains?: string | undefined;
  /**
   * The git commit SHA.
   */
  gitCommitSha?: string | undefined;
  /**
   * The docker registry image name.
   */
  dockerRegistryImageName?: string | undefined;
  /**
   * The docker registry image tag.
   */
  dockerRegistryImageTag?: string | undefined;
  /**
   * The flag to indicate if the application is static.
   */
  isStatic?: boolean | undefined;
  /**
   * The install command.
   */
  installCommand?: string | undefined;
  /**
   * The build command.
   */
  buildCommand?: string | undefined;
  /**
   * The start command.
   */
  startCommand?: string | undefined;
  /**
   * The ports mappings.
   */
  portsMappings?: string | undefined;
  /**
   * The base directory for all commands.
   */
  baseDirectory?: string | undefined;
  /**
   * The publish directory.
   */
  publishDirectory?: string | undefined;
  /**
   * Health check enabled.
   */
  healthCheckEnabled?: boolean | undefined;
  /**
   * Health check path.
   */
  healthCheckPath?: string | undefined;
  /**
   * Health check port.
   */
  healthCheckPort?: string | null | undefined;
  /**
   * Health check host.
   */
  healthCheckHost?: string | null | undefined;
  /**
   * Health check method.
   */
  healthCheckMethod?: string | undefined;
  /**
   * Health check return code.
   */
  healthCheckReturnCode?: number | undefined;
  /**
   * Health check scheme.
   */
  healthCheckScheme?: string | undefined;
  /**
   * Health check response text.
   */
  healthCheckResponseText?: string | null | undefined;
  /**
   * Health check interval in seconds.
   */
  healthCheckInterval?: number | undefined;
  /**
   * Health check timeout in seconds.
   */
  healthCheckTimeout?: number | undefined;
  /**
   * Health check retries count.
   */
  healthCheckRetries?: number | undefined;
  /**
   * Health check start period in seconds.
   */
  healthCheckStartPeriod?: number | undefined;
  /**
   * Memory limit.
   */
  limitsMemory?: string | undefined;
  /**
   * Memory swap limit.
   */
  limitsMemorySwap?: string | undefined;
  /**
   * Memory swappiness.
   */
  limitsMemorySwappiness?: number | undefined;
  /**
   * Memory reservation.
   */
  limitsMemoryReservation?: string | undefined;
  /**
   * CPU limit.
   */
  limitsCpus?: string | undefined;
  /**
   * CPU set.
   */
  limitsCpuset?: string | null | undefined;
  /**
   * CPU shares.
   */
  limitsCpuShares?: number | undefined;
  /**
   * Custom labels.
   */
  customLabels?: string | undefined;
  /**
   * Custom docker run options.
   */
  customDockerRunOptions?: string | undefined;
  /**
   * Post deployment command.
   */
  postDeploymentCommand?: string | undefined;
  /**
   * Post deployment command container.
   */
  postDeploymentCommandContainer?: string | undefined;
  /**
   * Pre deployment command.
   */
  preDeploymentCommand?: string | undefined;
  /**
   * Pre deployment command container.
   */
  preDeploymentCommandContainer?: string | undefined;
  /**
   * Manual webhook secret for Github.
   */
  manualWebhookSecretGithub?: string | undefined;
  /**
   * Manual webhook secret for Gitlab.
   */
  manualWebhookSecretGitlab?: string | undefined;
  /**
   * Manual webhook secret for Bitbucket.
   */
  manualWebhookSecretBitbucket?: string | undefined;
  /**
   * Manual webhook secret for Gitea.
   */
  manualWebhookSecretGitea?: string | undefined;
  /**
   * How to set redirect with Traefik / Caddy. www<->non-www.
   */
  redirect?: UpdateApplicationByUuidRedirect | null | undefined;
  /**
   * The flag to indicate if the application should be deployed instantly.
   */
  instantDeploy?: boolean | undefined;
  /**
   * The Dockerfile content.
   */
  dockerfile?: string | undefined;
  /**
   * The Docker Compose location.
   */
  dockerComposeLocation?: string | undefined;
  /**
   * The Docker Compose raw content.
   */
  dockerComposeRaw?: string | undefined;
  /**
   * The Docker Compose custom start command.
   */
  dockerComposeCustomStartCommand?: string | undefined;
  /**
   * The Docker Compose custom build command.
   */
  dockerComposeCustomBuildCommand?: string | undefined;
  /**
   * The Docker Compose domains.
   */
  dockerComposeDomains?: Array<any> | undefined;
  /**
   * The watch paths.
   */
  watchPaths?: string | undefined;
  /**
   * Use build server.
   */
  useBuildServer?: boolean | null | undefined;
};

export type UpdateApplicationByUuidRequest = {
  /**
   * UUID of the application.
   */
  uuid: string;
  /**
   * Application updated.
   */
  requestBody: UpdateApplicationByUuidRequestBody;
};

/**
 * Application updated.
 */
export type UpdateApplicationByUuidResponseBody = {
  uuid?: string | undefined;
};

/** @internal */
export const UpdateApplicationByUuidBuildPack$inboundSchema: z.ZodNativeEnum<
  typeof UpdateApplicationByUuidBuildPack
> = z.nativeEnum(UpdateApplicationByUuidBuildPack);

/** @internal */
export const UpdateApplicationByUuidBuildPack$outboundSchema: z.ZodNativeEnum<
  typeof UpdateApplicationByUuidBuildPack
> = UpdateApplicationByUuidBuildPack$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApplicationByUuidBuildPack$ {
  /** @deprecated use `UpdateApplicationByUuidBuildPack$inboundSchema` instead. */
  export const inboundSchema = UpdateApplicationByUuidBuildPack$inboundSchema;
  /** @deprecated use `UpdateApplicationByUuidBuildPack$outboundSchema` instead. */
  export const outboundSchema = UpdateApplicationByUuidBuildPack$outboundSchema;
}

/** @internal */
export const UpdateApplicationByUuidRedirect$inboundSchema: z.ZodNativeEnum<
  typeof UpdateApplicationByUuidRedirect
> = z.nativeEnum(UpdateApplicationByUuidRedirect);

/** @internal */
export const UpdateApplicationByUuidRedirect$outboundSchema: z.ZodNativeEnum<
  typeof UpdateApplicationByUuidRedirect
> = UpdateApplicationByUuidRedirect$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApplicationByUuidRedirect$ {
  /** @deprecated use `UpdateApplicationByUuidRedirect$inboundSchema` instead. */
  export const inboundSchema = UpdateApplicationByUuidRedirect$inboundSchema;
  /** @deprecated use `UpdateApplicationByUuidRedirect$outboundSchema` instead. */
  export const outboundSchema = UpdateApplicationByUuidRedirect$outboundSchema;
}

/** @internal */
export const UpdateApplicationByUuidRequestBody$inboundSchema: z.ZodType<
  UpdateApplicationByUuidRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  project_uuid: z.string().optional(),
  server_uuid: z.string().optional(),
  environment_name: z.string().optional(),
  github_app_uuid: z.string().optional(),
  git_repository: z.string().optional(),
  git_branch: z.string().optional(),
  ports_exposes: z.string().optional(),
  destination_uuid: z.string().optional(),
  build_pack: UpdateApplicationByUuidBuildPack$inboundSchema.optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  domains: z.string().optional(),
  git_commit_sha: z.string().optional(),
  docker_registry_image_name: z.string().optional(),
  docker_registry_image_tag: z.string().optional(),
  is_static: z.boolean().optional(),
  install_command: z.string().optional(),
  build_command: z.string().optional(),
  start_command: z.string().optional(),
  ports_mappings: z.string().optional(),
  base_directory: z.string().optional(),
  publish_directory: z.string().optional(),
  health_check_enabled: z.boolean().optional(),
  health_check_path: z.string().optional(),
  health_check_port: z.nullable(z.string()).optional(),
  health_check_host: z.nullable(z.string()).optional(),
  health_check_method: z.string().optional(),
  health_check_return_code: z.number().int().optional(),
  health_check_scheme: z.string().optional(),
  health_check_response_text: z.nullable(z.string()).optional(),
  health_check_interval: z.number().int().optional(),
  health_check_timeout: z.number().int().optional(),
  health_check_retries: z.number().int().optional(),
  health_check_start_period: z.number().int().optional(),
  limits_memory: z.string().optional(),
  limits_memory_swap: z.string().optional(),
  limits_memory_swappiness: z.number().int().optional(),
  limits_memory_reservation: z.string().optional(),
  limits_cpus: z.string().optional(),
  limits_cpuset: z.nullable(z.string()).optional(),
  limits_cpu_shares: z.number().int().optional(),
  custom_labels: z.string().optional(),
  custom_docker_run_options: z.string().optional(),
  post_deployment_command: z.string().optional(),
  post_deployment_command_container: z.string().optional(),
  pre_deployment_command: z.string().optional(),
  pre_deployment_command_container: z.string().optional(),
  manual_webhook_secret_github: z.string().optional(),
  manual_webhook_secret_gitlab: z.string().optional(),
  manual_webhook_secret_bitbucket: z.string().optional(),
  manual_webhook_secret_gitea: z.string().optional(),
  redirect: z.nullable(UpdateApplicationByUuidRedirect$inboundSchema)
    .optional(),
  instant_deploy: z.boolean().optional(),
  dockerfile: z.string().optional(),
  docker_compose_location: z.string().optional(),
  docker_compose_raw: z.string().optional(),
  docker_compose_custom_start_command: z.string().optional(),
  docker_compose_custom_build_command: z.string().optional(),
  docker_compose_domains: z.array(z.any()).optional(),
  watch_paths: z.string().optional(),
  use_build_server: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    "project_uuid": "projectUuid",
    "server_uuid": "serverUuid",
    "environment_name": "environmentName",
    "github_app_uuid": "githubAppUuid",
    "git_repository": "gitRepository",
    "git_branch": "gitBranch",
    "ports_exposes": "portsExposes",
    "destination_uuid": "destinationUuid",
    "build_pack": "buildPack",
    "git_commit_sha": "gitCommitSha",
    "docker_registry_image_name": "dockerRegistryImageName",
    "docker_registry_image_tag": "dockerRegistryImageTag",
    "is_static": "isStatic",
    "install_command": "installCommand",
    "build_command": "buildCommand",
    "start_command": "startCommand",
    "ports_mappings": "portsMappings",
    "base_directory": "baseDirectory",
    "publish_directory": "publishDirectory",
    "health_check_enabled": "healthCheckEnabled",
    "health_check_path": "healthCheckPath",
    "health_check_port": "healthCheckPort",
    "health_check_host": "healthCheckHost",
    "health_check_method": "healthCheckMethod",
    "health_check_return_code": "healthCheckReturnCode",
    "health_check_scheme": "healthCheckScheme",
    "health_check_response_text": "healthCheckResponseText",
    "health_check_interval": "healthCheckInterval",
    "health_check_timeout": "healthCheckTimeout",
    "health_check_retries": "healthCheckRetries",
    "health_check_start_period": "healthCheckStartPeriod",
    "limits_memory": "limitsMemory",
    "limits_memory_swap": "limitsMemorySwap",
    "limits_memory_swappiness": "limitsMemorySwappiness",
    "limits_memory_reservation": "limitsMemoryReservation",
    "limits_cpus": "limitsCpus",
    "limits_cpuset": "limitsCpuset",
    "limits_cpu_shares": "limitsCpuShares",
    "custom_labels": "customLabels",
    "custom_docker_run_options": "customDockerRunOptions",
    "post_deployment_command": "postDeploymentCommand",
    "post_deployment_command_container": "postDeploymentCommandContainer",
    "pre_deployment_command": "preDeploymentCommand",
    "pre_deployment_command_container": "preDeploymentCommandContainer",
    "manual_webhook_secret_github": "manualWebhookSecretGithub",
    "manual_webhook_secret_gitlab": "manualWebhookSecretGitlab",
    "manual_webhook_secret_bitbucket": "manualWebhookSecretBitbucket",
    "manual_webhook_secret_gitea": "manualWebhookSecretGitea",
    "instant_deploy": "instantDeploy",
    "docker_compose_location": "dockerComposeLocation",
    "docker_compose_raw": "dockerComposeRaw",
    "docker_compose_custom_start_command": "dockerComposeCustomStartCommand",
    "docker_compose_custom_build_command": "dockerComposeCustomBuildCommand",
    "docker_compose_domains": "dockerComposeDomains",
    "watch_paths": "watchPaths",
    "use_build_server": "useBuildServer",
  });
});

/** @internal */
export type UpdateApplicationByUuidRequestBody$Outbound = {
  project_uuid?: string | undefined;
  server_uuid?: string | undefined;
  environment_name?: string | undefined;
  github_app_uuid?: string | undefined;
  git_repository?: string | undefined;
  git_branch?: string | undefined;
  ports_exposes?: string | undefined;
  destination_uuid?: string | undefined;
  build_pack?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  domains?: string | undefined;
  git_commit_sha?: string | undefined;
  docker_registry_image_name?: string | undefined;
  docker_registry_image_tag?: string | undefined;
  is_static?: boolean | undefined;
  install_command?: string | undefined;
  build_command?: string | undefined;
  start_command?: string | undefined;
  ports_mappings?: string | undefined;
  base_directory?: string | undefined;
  publish_directory?: string | undefined;
  health_check_enabled?: boolean | undefined;
  health_check_path?: string | undefined;
  health_check_port?: string | null | undefined;
  health_check_host?: string | null | undefined;
  health_check_method?: string | undefined;
  health_check_return_code?: number | undefined;
  health_check_scheme?: string | undefined;
  health_check_response_text?: string | null | undefined;
  health_check_interval?: number | undefined;
  health_check_timeout?: number | undefined;
  health_check_retries?: number | undefined;
  health_check_start_period?: number | undefined;
  limits_memory?: string | undefined;
  limits_memory_swap?: string | undefined;
  limits_memory_swappiness?: number | undefined;
  limits_memory_reservation?: string | undefined;
  limits_cpus?: string | undefined;
  limits_cpuset?: string | null | undefined;
  limits_cpu_shares?: number | undefined;
  custom_labels?: string | undefined;
  custom_docker_run_options?: string | undefined;
  post_deployment_command?: string | undefined;
  post_deployment_command_container?: string | undefined;
  pre_deployment_command?: string | undefined;
  pre_deployment_command_container?: string | undefined;
  manual_webhook_secret_github?: string | undefined;
  manual_webhook_secret_gitlab?: string | undefined;
  manual_webhook_secret_bitbucket?: string | undefined;
  manual_webhook_secret_gitea?: string | undefined;
  redirect?: string | null | undefined;
  instant_deploy?: boolean | undefined;
  dockerfile?: string | undefined;
  docker_compose_location?: string | undefined;
  docker_compose_raw?: string | undefined;
  docker_compose_custom_start_command?: string | undefined;
  docker_compose_custom_build_command?: string | undefined;
  docker_compose_domains?: Array<any> | undefined;
  watch_paths?: string | undefined;
  use_build_server?: boolean | null | undefined;
};

/** @internal */
export const UpdateApplicationByUuidRequestBody$outboundSchema: z.ZodType<
  UpdateApplicationByUuidRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateApplicationByUuidRequestBody
> = z.object({
  projectUuid: z.string().optional(),
  serverUuid: z.string().optional(),
  environmentName: z.string().optional(),
  githubAppUuid: z.string().optional(),
  gitRepository: z.string().optional(),
  gitBranch: z.string().optional(),
  portsExposes: z.string().optional(),
  destinationUuid: z.string().optional(),
  buildPack: UpdateApplicationByUuidBuildPack$outboundSchema.optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  domains: z.string().optional(),
  gitCommitSha: z.string().optional(),
  dockerRegistryImageName: z.string().optional(),
  dockerRegistryImageTag: z.string().optional(),
  isStatic: z.boolean().optional(),
  installCommand: z.string().optional(),
  buildCommand: z.string().optional(),
  startCommand: z.string().optional(),
  portsMappings: z.string().optional(),
  baseDirectory: z.string().optional(),
  publishDirectory: z.string().optional(),
  healthCheckEnabled: z.boolean().optional(),
  healthCheckPath: z.string().optional(),
  healthCheckPort: z.nullable(z.string()).optional(),
  healthCheckHost: z.nullable(z.string()).optional(),
  healthCheckMethod: z.string().optional(),
  healthCheckReturnCode: z.number().int().optional(),
  healthCheckScheme: z.string().optional(),
  healthCheckResponseText: z.nullable(z.string()).optional(),
  healthCheckInterval: z.number().int().optional(),
  healthCheckTimeout: z.number().int().optional(),
  healthCheckRetries: z.number().int().optional(),
  healthCheckStartPeriod: z.number().int().optional(),
  limitsMemory: z.string().optional(),
  limitsMemorySwap: z.string().optional(),
  limitsMemorySwappiness: z.number().int().optional(),
  limitsMemoryReservation: z.string().optional(),
  limitsCpus: z.string().optional(),
  limitsCpuset: z.nullable(z.string()).optional(),
  limitsCpuShares: z.number().int().optional(),
  customLabels: z.string().optional(),
  customDockerRunOptions: z.string().optional(),
  postDeploymentCommand: z.string().optional(),
  postDeploymentCommandContainer: z.string().optional(),
  preDeploymentCommand: z.string().optional(),
  preDeploymentCommandContainer: z.string().optional(),
  manualWebhookSecretGithub: z.string().optional(),
  manualWebhookSecretGitlab: z.string().optional(),
  manualWebhookSecretBitbucket: z.string().optional(),
  manualWebhookSecretGitea: z.string().optional(),
  redirect: z.nullable(UpdateApplicationByUuidRedirect$outboundSchema)
    .optional(),
  instantDeploy: z.boolean().optional(),
  dockerfile: z.string().optional(),
  dockerComposeLocation: z.string().optional(),
  dockerComposeRaw: z.string().optional(),
  dockerComposeCustomStartCommand: z.string().optional(),
  dockerComposeCustomBuildCommand: z.string().optional(),
  dockerComposeDomains: z.array(z.any()).optional(),
  watchPaths: z.string().optional(),
  useBuildServer: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    projectUuid: "project_uuid",
    serverUuid: "server_uuid",
    environmentName: "environment_name",
    githubAppUuid: "github_app_uuid",
    gitRepository: "git_repository",
    gitBranch: "git_branch",
    portsExposes: "ports_exposes",
    destinationUuid: "destination_uuid",
    buildPack: "build_pack",
    gitCommitSha: "git_commit_sha",
    dockerRegistryImageName: "docker_registry_image_name",
    dockerRegistryImageTag: "docker_registry_image_tag",
    isStatic: "is_static",
    installCommand: "install_command",
    buildCommand: "build_command",
    startCommand: "start_command",
    portsMappings: "ports_mappings",
    baseDirectory: "base_directory",
    publishDirectory: "publish_directory",
    healthCheckEnabled: "health_check_enabled",
    healthCheckPath: "health_check_path",
    healthCheckPort: "health_check_port",
    healthCheckHost: "health_check_host",
    healthCheckMethod: "health_check_method",
    healthCheckReturnCode: "health_check_return_code",
    healthCheckScheme: "health_check_scheme",
    healthCheckResponseText: "health_check_response_text",
    healthCheckInterval: "health_check_interval",
    healthCheckTimeout: "health_check_timeout",
    healthCheckRetries: "health_check_retries",
    healthCheckStartPeriod: "health_check_start_period",
    limitsMemory: "limits_memory",
    limitsMemorySwap: "limits_memory_swap",
    limitsMemorySwappiness: "limits_memory_swappiness",
    limitsMemoryReservation: "limits_memory_reservation",
    limitsCpus: "limits_cpus",
    limitsCpuset: "limits_cpuset",
    limitsCpuShares: "limits_cpu_shares",
    customLabels: "custom_labels",
    customDockerRunOptions: "custom_docker_run_options",
    postDeploymentCommand: "post_deployment_command",
    postDeploymentCommandContainer: "post_deployment_command_container",
    preDeploymentCommand: "pre_deployment_command",
    preDeploymentCommandContainer: "pre_deployment_command_container",
    manualWebhookSecretGithub: "manual_webhook_secret_github",
    manualWebhookSecretGitlab: "manual_webhook_secret_gitlab",
    manualWebhookSecretBitbucket: "manual_webhook_secret_bitbucket",
    manualWebhookSecretGitea: "manual_webhook_secret_gitea",
    instantDeploy: "instant_deploy",
    dockerComposeLocation: "docker_compose_location",
    dockerComposeRaw: "docker_compose_raw",
    dockerComposeCustomStartCommand: "docker_compose_custom_start_command",
    dockerComposeCustomBuildCommand: "docker_compose_custom_build_command",
    dockerComposeDomains: "docker_compose_domains",
    watchPaths: "watch_paths",
    useBuildServer: "use_build_server",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApplicationByUuidRequestBody$ {
  /** @deprecated use `UpdateApplicationByUuidRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateApplicationByUuidRequestBody$inboundSchema;
  /** @deprecated use `UpdateApplicationByUuidRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    UpdateApplicationByUuidRequestBody$outboundSchema;
  /** @deprecated use `UpdateApplicationByUuidRequestBody$Outbound` instead. */
  export type Outbound = UpdateApplicationByUuidRequestBody$Outbound;
}

export function updateApplicationByUuidRequestBodyToJSON(
  updateApplicationByUuidRequestBody: UpdateApplicationByUuidRequestBody,
): string {
  return JSON.stringify(
    UpdateApplicationByUuidRequestBody$outboundSchema.parse(
      updateApplicationByUuidRequestBody,
    ),
  );
}

export function updateApplicationByUuidRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApplicationByUuidRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateApplicationByUuidRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApplicationByUuidRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateApplicationByUuidRequest$inboundSchema: z.ZodType<
  UpdateApplicationByUuidRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  RequestBody: z.lazy(() => UpdateApplicationByUuidRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateApplicationByUuidRequest$Outbound = {
  uuid: string;
  RequestBody: UpdateApplicationByUuidRequestBody$Outbound;
};

/** @internal */
export const UpdateApplicationByUuidRequest$outboundSchema: z.ZodType<
  UpdateApplicationByUuidRequest$Outbound,
  z.ZodTypeDef,
  UpdateApplicationByUuidRequest
> = z.object({
  uuid: z.string(),
  requestBody: z.lazy(() => UpdateApplicationByUuidRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApplicationByUuidRequest$ {
  /** @deprecated use `UpdateApplicationByUuidRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateApplicationByUuidRequest$inboundSchema;
  /** @deprecated use `UpdateApplicationByUuidRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateApplicationByUuidRequest$outboundSchema;
  /** @deprecated use `UpdateApplicationByUuidRequest$Outbound` instead. */
  export type Outbound = UpdateApplicationByUuidRequest$Outbound;
}

export function updateApplicationByUuidRequestToJSON(
  updateApplicationByUuidRequest: UpdateApplicationByUuidRequest,
): string {
  return JSON.stringify(
    UpdateApplicationByUuidRequest$outboundSchema.parse(
      updateApplicationByUuidRequest,
    ),
  );
}

export function updateApplicationByUuidRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApplicationByUuidRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApplicationByUuidRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApplicationByUuidRequest' from JSON`,
  );
}

/** @internal */
export const UpdateApplicationByUuidResponseBody$inboundSchema: z.ZodType<
  UpdateApplicationByUuidResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string().optional(),
});

/** @internal */
export type UpdateApplicationByUuidResponseBody$Outbound = {
  uuid?: string | undefined;
};

/** @internal */
export const UpdateApplicationByUuidResponseBody$outboundSchema: z.ZodType<
  UpdateApplicationByUuidResponseBody$Outbound,
  z.ZodTypeDef,
  UpdateApplicationByUuidResponseBody
> = z.object({
  uuid: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApplicationByUuidResponseBody$ {
  /** @deprecated use `UpdateApplicationByUuidResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    UpdateApplicationByUuidResponseBody$inboundSchema;
  /** @deprecated use `UpdateApplicationByUuidResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    UpdateApplicationByUuidResponseBody$outboundSchema;
  /** @deprecated use `UpdateApplicationByUuidResponseBody$Outbound` instead. */
  export type Outbound = UpdateApplicationByUuidResponseBody$Outbound;
}

export function updateApplicationByUuidResponseBodyToJSON(
  updateApplicationByUuidResponseBody: UpdateApplicationByUuidResponseBody,
): string {
  return JSON.stringify(
    UpdateApplicationByUuidResponseBody$outboundSchema.parse(
      updateApplicationByUuidResponseBody,
    ),
  );
}

export function updateApplicationByUuidResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApplicationByUuidResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateApplicationByUuidResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApplicationByUuidResponseBody' from JSON`,
  );
}
